### ISSUE TITLE
Remove .env file

### ISSUE THREAD

**Issue by khyamay** [hieptl/netflix-clone#1]
I do not think it is a good idea to commit `.env` file to the repo. I would highly recommend it to delete it. A good practice would be to include `.env` file in `.gitignore` file.

**Comment by hieptl** [comment]
Hi @khyamay, thank you for your suggestion. I really appreciate that. In fact, I know that the best practice is about we should remove .env files in the project by including them in .gitignore file. I did not include them in .gitignore file because the main purpose of the project is to help people learn about React and its ecosystem. Therefore. I showed .env files as examples / materials for the project. The project is not used for commercial purpose :smile: However, I removed them from the repository and I will write guidelines to help others create their .env files.
Thanks and Best Regards,
Hiep

**Comment by khyamay** [comment]
@hieptl No worries, yeah it's a good steps to write the guidlines to help other to create their own .env file. Also another suggestion would be to delete any project on firebase whose api were included on the .env as they were exposed now. You dont want others to use your resources from firebase 👍
